language: c

matrix:
  include:
    # Test GCC on GNU/Linux.
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - libgmp-dev
    # Test Clang on GNU/Linux.
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libgmp-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0"
    # Test GCC on OS/X.
    - os: osx
      osx_image: xcode9.2
      compiler: gcc
    # Test Clang on OS/X.
    - os: osx
      osx_image: xcode9.2
      compiler: clang

before_install:
    - eval "${MATRIX_EVAL}"

script:
- make
- make test
